### ISSUE TITLE
New-TssSession issue on 0.32.0-beta 

### ISSUE THREAD

**Issue by harrychandrapdx** [thycotic-ps/thycotic.secretserver#108]
After updating to the 0.32.0-beta module, New-TssSession failed with the following error: 

![image](https://user-images.githubusercontent.com/24290978/110079044-6ff90580-7d3d-11eb-853f-a67daaabfea8.png)

To test, I re-installed 0.12.0-beta and New-TssSession works just fine. I also tested it on 0.25.0-beta and it works. It failed on 0.30.0-beta version.  

![image](https://user-images.githubusercontent.com/24290978/110080555-77211300-7d3f-11eb-80ac-6fd414626db3.png)

Wondering if anyone else is seeing this issue? 

Thanks!
Harry

**Comment by jagger** [comment]
What version of secret server are you running this against?

**Comment by harrychandrapdx** [comment]
@jagger It is running 10.9.000002. I am unable to find the version reporting setting in admin -> configuration. I might not have full admin rights to Thycotic to see this setting. I found "Hide Secret Server Version Numbers" in Admin -> Configuration -> Security and it is set to "No".

**Comment by wsmelton** [comment]
Can you provide the verbose output

**Comment by wsmelton** [comment]
@harrychandrapdx `New-TssSession` was reworked with version 0.30.0 in order to add Windows Authentication and then later adding Client SDK integration. We will need more details on your environment and the verbose output in order to assist. 

Please open a new issue and provide the details in the bug template.
