### ISSUE TITLE
API Response Code Return

### ISSUE THREAD

**Issue by tcarolanthycotic** [thycotic-ps/thycotic.secretserver#113]
**Is your feature request related to a problem? Please describe.**
When making various queries through the module, (Set-TSSSecret, in particular) it would be nice to get a specific response to ensure that the behavior against the API will be reflected as per the request, without the function itself having had to have thrown an exception or failed. 

**Describe the solution you'd like**
A flag for REST Response codes to be optionally added to the returned for a called function.

**Describe alternatives you've considered**
Some of this information can already be attained through the Verbose logging, but this needs a fair bit of handling to interpret.

**Additional context**
It is noted that there are some Powershell limitations (mostly resolve in Powershell 7+) that makes this more straightforward.

**Comment by wsmelton** [comment]
`Invoke-RestMethod` is the restriction in this situation. 

Windows PowerShell version of the cmdlet strips out the response object returned by an API call and will return just the `code` and `message` if one is given by the endpoint. The only way to get the true response object of an API is using `Invoke-WebRequest`:

![image](https://user-images.githubusercontent.com/11204251/110817901-61857f00-8252-11eb-904e-3c56967b7ad5.png)

The negative on using that cmdlet is the object on a 200 response returned by the endpoint has to be processed more in order to get a proper PowerShell object. `irm` does that for us and outputs a `PSCustomObject`.

PowerShell 7+ gives additional options by adding parameters to capture things like `-StatusCodeVariable` but that is the minimum that can be retrieved. This means that it will only be made available when this version of PowerShell is utilized. I have no viable method of doing this in Windows PowerShell.

**Comment by wsmelton** [comment]
Well, the only viable option to making this usable for true cross-platform would be to convert all API calls to using `Invoke-WebRequest` and then dealing with raw JSON objects:

![image](https://user-images.githubusercontent.com/11204251/110819209-90e8bb80-8253-11eb-8061-19c1c939cf07.png)

**Comment by wsmelton** [comment]
Added functionality in #220 

You know will get a global variable generated after each command makes an API call that can be referenced `$tssLastResponse`.

https://github.com/thycotic-ps/thycotic.secretserver/blob/92bcab1c089bfd0f66190f46faf3dd121372376b/src/parts/ProcessResponse.ps1#L14-L21
