### ISSUE TITLE
Session Refresh does not update StartTime and TimeOfDeath

### ISSUE THREAD

**Issue by miked1313** [thycotic-ps/thycotic.secretserver#253]
### Verified issue does not already exist?

Yes

### What error did you receive

Functions that require -TssSession throw error Authentication failed or expired token

### Please run the command using -Verbose

N/A you can't run Verbose on $session.SessionRefresh()

### Provide a test case or steps to reproduce

$global:session = New-TssSession -SecretServer https://vault.company/SecretServer -Credential $cred
$global:session

Wait 20+ minutes if the Secret Server instance defaults to a 20 minute session timeout

$global:session.SessionRefresh()
$global:session

Observe that StartTime and TimeOfDeath is not updated after you run $global:session.SessionRefresh()

$global:session.IsValidToken() is also $false and should be $true

### Expected behavior

StartTime and TimeOfDeath is updated to the new values after refreshing a session token and IsValidToken() should return an accurate $true if the token is valid.  The TimeOfDeath timestamp is important for checking for token expiration and being able to renew it prior to it expiring.  I have a custom Get-Session function which checks/renews and if needed will create a brand new session and prompt for credentials.

### What Edition of Secret Server?

Professional

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by miked1313** [comment]
Thank you for fixing this.  Do you know when it will be released?

**Comment by wsmelton** [comment]
Released

**Comment by Zebrainbow** [comment]
Not sure how/why, but this bug seems to have reared it's ugly head...

Initially, token has an invalid time of death. 

PS C:\Windows\System32> $session
SecretServer                       SecretServerVersion TokenType StartTime             TimeOfDeath
------------                       ------------------- --------- ---------             -----------
                                           11.6.000039         SdkClient 2/14/2024 12:33:34 PM 1/1/0001 12:00:00 AM



It seems as though the session token is expired the moment you refresh it. 



SecretServer                       SecretServerVersion TokenType StartTime             TimeOfDeath
------------                       ------------------- --------- ---------             -----------
    ####                                                                               2/14/2024 12:28:44 PM 2/14/2024 12:28:44 PM

PS C:\> $session.sessionrefresh()
True
PS C:\> $session.isvalidtoken()
False
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
