### ISSUE TITLE
set-tsssecret fails for restricted secrets

### ISSUE THREAD

**Issue by jagger** [thycotic-ps/thycotic.secretserver#90]
When executing the following code I am getting errors for restricted secrets 
`Set-TssSecret -TssSession $SourceSession -HeartbeatEnabled:$false  -Id $secretid -comment "disabling heartbeat"`

The server is reporting errors about needing comment
_The remote server returned an error: (500) Internal Server Error. | The requested Secret requires a comment when viewed._

**Comment by wsmelton** [comment]
The PATCH endpoints used in the Set function do not provide any option to pass the restricted arguments. I am using a call to `Get-TssSecret` for three params (AutoChangeEnabled, AutoChangeNextPassword, and EnableInheritPermission) because the `PUT /secrets/{id}` has to be used.

Using `Get` call causes an additional audit entry since it is getting the password in plain text (view password audit or something). I don't want to add that for all the PATCH endpoints.

My plan right now is to add a part script for doing checkouts. It will call the `POST /secrets/{id}/check-out` but prior to that being used you have to create a view comment message using `POST /secret-access-requests/secrets/{id}/view-comment`. The part script will handle calling those two endpoints.
